version: '3.4'

services:
  abstractrest:
    image: onetimemessagerest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
